### ISSUE TITLE
run E2E test in aws lambda

### ISSUE THREAD

**Issue by timothydnguyen** [approzium/approzium#15]
**we want to bring up an app using approzium sdk to connect to a database without passing a password**
- the password should be stored in vault against the ARN of the IAM assigned to the lambda

something we're looking for here is that the sts identity stuff works out of the box with aws resources 

possible challenges
- py dependencies on aws lambda
- communication sdk <> authenticator

**Comment by timothydnguyen** [comment]
also run in ec2

**Comment by tyrannosaurus-becks** [comment]
So for testing, I'm going to mainly test the client side because it would be strange to run the authenticator in Lambda since Lambda functions can only last for up to 15 minutes (reference here)[https://aws.amazon.com/about-aws/whats-new/2018/10/aws-lambda-supports-functions-that-can-run-up-to-15-minutes/#:~:text=You%20can%20now%20configure%20your,Lambda%20function%20was%205%20minutes.]

**Comment by tyrannosaurus-becks** [comment]
I've confirmed that when running in AWS Lambda, the boto3 client will be able to pick up the assumed role as-written. So, our Python client _will work_ inside of AWS Lambda. 

Our recommended architecture would be that the Authenticator is run in a stable environment like EC2, and the client can be used in EC2 or Lambda. Going to update the docs to that effect.
